### ISSUE TITLE
[Question] Need help for editing META-INF/MANIFEST.MF part

### ISSUE THREAD

**Issue by SteveKunG** [octarine-noise/simpledeobf#2]
I don't really understand the part of Editing META-INF/MANIFEST.MF file and Change the TweakClass option to the tweaker. Did you have instruction pictures?

Also, how to use this file?
https://github.com/octarine-noise/BetterFoliage/blob/abf037d8a9640594a76b9f2524885da6f440bd41/src/main/kotlin/optifine/OptifineTweakerDevWrapper.kt

**Comment by octarine-noise** [comment]
I meant once you have a deobfuscated Optifine jar, go into the jar file, and edit its MANIFEST.MF file (which was copied over unchanged from the original) to use a different tweaker class. This is needed because the Optifine tweaker will not work in a deobfuscated environment.

That class you linked is basically just my reimplementation of the long-ago original Optifine tweaker, which used wholesale replacement of .class files. If it found any class that was being loaded in the Optifine jar, it used that one instead. Newer versions use binary patches to Minecraft classes, which is what the xdelta options are about (it will generate a jar that is compatible with this old way of doing things - replacement).

I didn't have pictures or tutorials. I just looked at FML code (and some other mods) to figure out how startup and mod loading worked.

**Comment by SteveKunG** [comment]
Nevermind, I'm just looking for zoom key binding field in the Optifine classes. Thanks!
